apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: okta
      openID:
        claims:
          email:
          - email
          name:
          - name
          - email
          preferredUsername:
          - preferred_username
          - email
        clientID: 0oa5kfxzbtgxOpzMz5d7
        clientSecret:
          name: openid-okta-secret
        extraScopes:
        - email
        - profile
        issuer: https://dev-34242021.okta.com                       
      type: OpenID